empty_tuples = ()
print(empty_tuples)
print(type(empty_tuples))
lst=list()
print(type(lst))
tpl=tuple()
print(type(tpl))
numbers = tuple([1, 2, 3, 4, 5, 6])
print(numbers)
mixed_tuple = (42, "Arpit", 6.95, False)
print(mixed_tuple)